
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';
export const PRODUCT_IMAGES = 'PRODUCT_IMAGES';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const PRODUCT_DETAILS_CATEGORY = 'PRODUCT_DETAILS_CATEGORY';
