// AUTH
export const SET_USER = 'SET_USER';
export const NO_AD_FOUND = 'NO_AD_FOUND';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';

// Add product

export const PRODUCT_IMAGES = 'PRODUCT_IMAGES';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const PRODUCT_DETAILS_CATEGORY = 'PRODUCT_DETAILS_CATEGORY';
